name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]

jobs:
  windows:
    runs-on: ubuntu-latest

    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2.2.0
      with:
        platform: x64

    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/windows" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake
        -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/toolchain-mingw32.cmake
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}/translucent.exe