name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted-arm64

    strategy:
      matrix:
        type:
          - name: windows
            toolchain: toolchain-mingw64.cmake
            file: translucent.exe

          - name: linux
            toolchain: toolchain-x86_64-linux.cmake
            file: translucent

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Cleanup
      shell: bash
      run: rm -rdf ${{ github.workspace }}/build

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "build-output-file=${{ github.workspace }}/build/${{ matrix.type.file }}" >> "$GITHUB_OUTPUT"
        echo "cmake-toolchain=${{ github.workspace }}/${{ matrix.type.toolchain }}" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake
        -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_TOOLCHAIN_FILE=${{ steps.strings.outputs.cmake-toolchain }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release --parallel

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.type.name }}
        path: ${{ steps.strings.outputs.build-output-file }}
        compression-level: 9

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GT }}
        tag_name: nightly
        files: ${{ steps.strings.outputs.build-output-file }}